<head>
    <?php echo $this->tag->javascriptInclude('js/jquery/jquery.min.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/bootstrap/bootstrap.min.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/dataTables/jquery.dataTables.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/dataTables/dataTables.bootstrap.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/dataTables/dataTables.tableTools.min.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/sweetalert/sweetalert.min.js'); ?>

    <?php echo $this->tag->stylesheetLink('css/bootstrap/bootstrap.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/dataTables/dataTables.bootstrap.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/dataTables/dataTables.tableTools.min.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/dataTables/dataTables.responsive.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/sweetalert/sweetalert.css'); ?>

</head>
<?php
$this->session->start();
$util = new Util();
$url = 'http://localhost/rest-api/Usuario/' . $this->session->get("cod_user") . '/Produto';
$produtos = $util->getAPI($url);
?>
<body style="margin: 15px">
    <input type="hidden" name="usua_cod" value="<?php print $this->session->get("cod_user"); ?>" id="usua_cod">
    <div class="row">
        <div class="col-lg-4"><br></div>
    </div>
    <div class="row" >
        <div class="col-lg-4">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal4">Adicionar produto</button>
        </div>
    </div>

    <div class="row" >
        <div class="col-lg-4"><br><br></div>
    </div>
    <div class="row ibox-content" >
        <div class="col-lg-12" >
            <table id="searchresults" class="table table-striped table-bordered table-hover dataTables-example" cellspacing="0" width="100%" >
                <thead>
                    <tr>
                        <th>PRODUTO</th>
                        <th>MARCA</th>
                        <th>USUÁRIO</th>
                        <th>AÇÃO</th>
                    </tr>
                </thead>
                <tbody>
                    <?php $nome = $util->getAPI('http://localhost/rest-api/Usuario/' . $this->session->get("cod_user"))['usua_nome']; ?>
                    <?php foreach ($produtos as $value) :
                        ?>
                        <tr>
                            <td><?php print $value['prod_nome']; ?></td>
                            <td><?php print $util->getAPI('http://localhost/rest-api/Marca/' . $value['marc_codigo'])['marc_nome']; ?></td>
                            <td> <?php print $nome; ?></td>
                            <td><a onclick="loadProduto('<?php print $value['prod_codigo']; ?>');">Alterar</a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="modal inmodal in" id="myModal4" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only"></span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">Cadastro de produto</h4>
                    <small>Campo com * de preenchimento obrigatório.</small>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger" id="alert_danger_form_produto"></div>
                    <form method="POST">

                        <div class="row">
                            <div class="col-lg-12" >
                                <label class="font-noraml" for="nome">* Nome do Produto</label>
                                <input class="form-control" type="text" required="true" name="nome" id="nome">
                            </div>
                            <div class="col-lg-12" >
                                <label class="font-noraml" for="marca_produto">* Marca do Produto</label>
                                <select class="form-control" id="marca_produto" required="true">
                                    <option value="0">--Selecione--</option>
                                </select>
                            </div>
                            <div class="col-lg-12" >
                                <label class="font-noraml" for="preco">* Preço do Produto</label>
                                <input class="form-control" type="text" required="true" name="preco" id="preco">
                            </div>
                            <div class="col-lg-12" >
                                <label class="font-noraml" for="qtd_produto">* Quantidade do Produto</label>
                                <input class="form-control" type="number" required="true" name="qtd_produto" id="qtd_produto">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">Fechar</button>
                    <input type="hidden" name="acao" id="acao" >
                    <button type="button" onclick="create_produto();" id="create-user" class="btn btn-primary">Enviar</button>
                </div>
            </div>
        </div>
    </div>
</body>
<script type="text/javascript">
    $(document).ready(function () {
        $('#alert_danger_form_produto').hide();
        $('#searchresults').DataTable();
        getMarca();
    });

    function loadProduto(prod_codigo) {
        var url = "/rest-api/Produto/" + prod_codigo;
        $.ajax({
            type: "GET",
            url: url,
            success: function (data) {
                console.log(data);
                $('#nome').val(data.prod_nome);
                $('#marca_produto').val(data.marc_codigo);
                $('#preco').val(data.prod_preco);
                $('#qtd_produto').val(data.prod_quantidade);
                $('#acao').val(prod_codigo);
                $('#myModal4').modal('show');
            },
            error: function (error) {
                console.log(error);
            },
            dataType: 'JSON'
        });
    }
    function getMarca() {
        var url = "/rest-api/Marca";
        $.ajax({
            type: "GET",
            url: url,
            success: function (data) {
                var html_option = $('#marca_produto').html();
                for (var i = 0; i < data.length; i++) {
                    html_option += "<option value='" + data[i].marc_codigo + "' >" + data[i].marc_nome + " </option>";
                }
                $('#marca_produto').html(html_option);
            },
            error: function (error) {
                console.log(error);
            },
            dataType: 'JSON'
        });
    }
    function create_produto() {
        var validacao = isFormValid();
        if (validacao == "") {
            var acao = trim($('#acao').val());
            var url = "/rest-api/Produto";
            if (acao.length > 0) {
                url += '/' + $('#acao').val();
            }
            console.log(url);
            var prod_nome = $('#nome').val();
            var marc_codigo = $('#marca_produto').val();
            var prod_preco = $('#preco').val();
            var prod_quantidade = $('#qtd_produto').val();
            var usua_codigo = $('#usua_cod').val();
            var data = {prod_nome: prod_nome, marc_codigo: marc_codigo, prod_preco: prod_preco, prod_quantidade: prod_quantidade, usua_codigo: usua_codigo};
            console.log(data);
            $.ajax({
                type: "POST",
                url: url,
                data: data,
                success: function (data) {
                    if (data.status == 'SUCCESS') {
                        swal({
                            title: 'SUCESSO!',
                            text: 'Seu produto foi cadastrado com sucesso!',
                            type: 'success',
                            closeOnConfirm: false
                        }, function () {
                            window.location.href = "http://localhost/rest-api/Produto/lista";
                        });

                    } else {
                        swal("INFORMAÇÃO", "Usuário já existente na base de dados", "info");
                    }
                },
                error: function (error) {
                    console.log("Error" + error);
                },
                dataType: 'JSON'
            });
        }
    }
    function isFormValid() {
        var returned = "";
        var produto = trim($('#nome').val());
        var marca = trim($('#marca_produto').val());
        var preco = trim($('#preco').val());
        var qtd_produto = trim($('#qtd_produto').val());

        if (produto.length == 0) {
            $('#nome').addClass('form_error_input_cashier');
            returned += "<li>Nome do produto de preenchimento obrigatório!</li>";
        } else {
            $('#nome').removeClass('form_error_input_cashier');
        }
        if ($('#marca_produto').val() == 0) {
            $('#marca_produto').addClass('form_error_input_cashier');
            returned += "<li>Marca do produto de preenchimento obrigatório!</li>";
        } else {
            $('#marca_produto').removeClass('form_error_input_cashier');
        }
        if (preco.length == 0) {
            $('#preco').addClass('form_error_input_cashier');
            returned += "<li>Preço do produto de preenchimento obrigatório!</li>";
        } else {
            $('#preco').removeClass('form_error_input_cashier');
        }
        if (qtd_produto.length == 0) {
            $('#qtd_produto').addClass('form_error_input_cashier');
            returned += "<li>Quantida do produto de preenchimento obrigatório!</li>";
        } else {
            $('#qtd_produto').removeClass('form_error_input_cashier');
        }

        if (returned != "") {
            $('#alert_danger_form_produto').show();
            $('#alert_danger_form_produto').html('<ul>' + returned + '</ul>');
        } else {
            $('#alert_danger_form_produto').hide();
            $('#alert_danger_form_produto').html(returned);
        }
        if ($('#alert_danger_form_produto ul').length > 0) {
            $("#nome").attr('onchange', 'isFormValid();');
            $("#marca_produto").attr('onchange', 'isFormValid();');
            $("#preco").attr('onchange', 'isFormValid();');
            $('#qtd_produto').attr('onchange', 'isFormValid();');
        } else {
            $("#nome").removeAttr('onchange');
            $("#marca_produto").removeAttr('onchange');
            $("#preco").removeAttr('onchange');
            $('#qtd_produto').removeAttr('onchange');
        }
        return returned;
    }
    function trim(str) {
        return str.replace(/^\s+|\s+$/g, "");
    }

</script>