<head>
    <?php echo $this->tag->javascriptInclude('js/jquery/jquery.min.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/bootstrap/bootstrap.min.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/dataTables/jquery.dataTables.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/dataTables/dataTables.bootstrap.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/dataTables/dataTables.tableTools.min.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/sweetalert/sweetalert.min.js'); ?>

    <?php echo $this->tag->stylesheetLink('css/bootstrap/bootstrap.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/dataTables/dataTables.bootstrap.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/dataTables/dataTables.tableTools.min.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/dataTables/dataTables.responsive.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/sweetalert/sweetalert.css'); ?>
</head>
<?php
$util = new Util();
$url = 'http://localhost/rest-api/Marca';
$marcas = $util->getAPI($url);
?>
<body style="margin: 15px">
    <div class="row">
        <div class="col-lg-4"><br></div>
    </div>
    <div class="row" >
        <div class="col-lg-4">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal4">Adicionar marcas</button>
        </div>
    </div>

    <div class="row" >
        <div class="col-lg-4"><br><br></div>
    </div>
    <div class="row ibox-content" >
        <div class="col-lg-12" >
            <table id="searchresults" class="table table-striped table-bordered table-hover dataTables-example" cellspacing="0" width="100%" >
                <thead>
                    <tr>
                        <th>MARCA</th>
                        <th>AÇÃO</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($marcas as $key => $value) : ?>
                        <tr>
                            <td><?php print $value['marc_nome']; ?></td>
                            <td><a onclick="loadMarca('<?php print $value['marc_codigo']; ?>');">Alterar</a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="modal inmodal in" id="myModal4" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only"></span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">Cadastro de marcas</h4>
                    <small>Campo com * de preenchimento obrigatório.</small>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger" id="alert_danger_form_marcas"></div>
                    <form method="POST">

                        <div class="row">
                            <div class="col-lg-12" >
                                <label class="font-noraml" for="nome">* Marca</label>
                                <input class="form-control" type="text" required="true" name="nome" id="nome">
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="acao" id="acao">
                    <button type="button" class="btn btn-white" data-dismiss="modal">Fechar</button>
                    <button type="button" onclick="create_marca()" id="create-user" class="btn btn-primary">Enviar</button>
                </div>
            </div>
        </div>
    </div>
</body>
<script type="text/javascript">
    $(document).ready(function () {
        $('#alert_danger_form_marcas').hide();
        $('#searchresults').DataTable();
        getMarca();
    });

    function loadMarca(marc_codigo) {
        var url = "/rest-api/Marca/" + marc_codigo;
        $.ajax({
            type: "GET",
            url: url,
            success: function (data) {
                console.log(data);
                $('#nome').val(data.marc_nome);
                $('#acao').val(data.marc_codigo);
                $('#myModal4').modal('show');
            },
            error: function (error) {
                console.log(error);
            },
            dataType: 'JSON'
        });
    }
    function create_marca() {
        var validacao = isFormValid();
        if (validacao == "") {
            var acao = trim($('#acao').val());
            var url = "/rest-api/Marca";
            if (acao.length > 0) {
                url += '/' + $('#acao').val();
            }
            console.log(url);
            var marc_nome = $('#nome').val();
            var data = {marc_nome: marc_nome};
            $.ajax({
                type: "POST",
                url: url,
                data: data,
                success: function (data) {
                    if (data.status == 'SUCCESS') {
                        swal({
                            title: 'SUCESSO!',
                            text: 'Marca foi cadastrado com sucesso!',
                            type: 'success',
                            closeOnConfirm: false
                        }, function () {
                            window.location.href = "http://localhost/rest-api/Marca/lista";
                        });

                    } else {
                        swal("INFORMAÇÃO", "Marca já existente na base de dados", "info");
                    }
                },
                error: function (error) {
                    swal("INFORMAÇÃO", "Marca já existente na base de dados", "info");
                },
                dataType: 'JSON'
            });
        }
    }
    function isFormValid() {
        var returned = "";
        var nome = trim($('#nome').val());

        if (nome.length == 0) {
            $('#nome').addClass('form_error_input_cashier');
            returned += "<li>Nome do marcas de preenchimento obrigatório!</li>";
        } else {
            $('#nome').removeClass('form_error_input_cashier');
        }

        if (returned != "") {
            $('#alert_danger_form_marcas').show();
            $('#alert_danger_form_marcas').html('<ul>' + returned + '</ul>');
        } else {
            $('#alert_danger_form_marcas').hide();
            $('#alert_danger_form_marcas').html(returned);
        }
        if ($('#alert_danger_form_marcas ul').length > 0) {
            $("#nome").attr('onchange', 'isFormValid();');
        } else {
            $("#nome").removeAttr('onchange');
        }
        return returned;
    }

    function trim(str) {
        return str.replace(/^\s+|\s+$/g, "");
    }

</script>