<head>
    <?php echo $this->tag->javascriptInclude('js/jquery/jquery.min.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/bootstrap/bootstrap.min.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/dataTables/jquery.dataTables.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/dataTables/dataTables.bootstrap.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/dataTables/dataTables.tableTools.min.js'); ?>
    <?php echo $this->tag->javascriptInclude('js/sweetalert/sweetalert.min.js'); ?>

    <?php echo $this->tag->stylesheetLink('css/bootstrap/bootstrap.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/dataTables/dataTables.bootstrap.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/dataTables/dataTables.tableTools.min.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/dataTables/dataTables.responsive.css'); ?>
    <?php echo $this->tag->stylesheetLink('css/sweetalert/sweetalert.css'); ?>
</head>
<?php
$util = new Util();
$url = 'http://localhost/rest-api/Usuario';
$usuarios = $util->getAPI($url);
?>
<body style="margin: 15px">
    <div class="row">
        <div class="col-lg-4"><br></div>
    </div>
    <div class="row" >
        <div class="col-lg-4">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal4">Adicionar usuário</button>
        </div>
    </div>

    <div class="row" >
        <div class="col-lg-4"><br><br></div>
    </div>
    <div class="row ibox-content" >
        <div class="col-lg-12" >
            <table id="searchresults" class="table table-striped table-bordered table-hover dataTables-example" cellspacing="0" width="100%" >
                <thead>
                    <tr>
                        <th>NOME</th>
                        <th>EMAIL</th>
                        <th>STATUS</th>
                        <th>AÇÃO</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($usuarios as $key => $value) : ?>
                        <tr>
                            <td><?php print $value['usua_nome']; ?></td>
                            <td><?php print $value['usua_email']; ?></td>
                            <td><?php ($value['usua_habilitado'] == 1) ? print 'Ativo' : print 'Inativo'; ?></td>
                            <td><a onclick="loadUsuario('<?php print $value['usua_codigo']; ?>');">Alterar</a></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <div class="modal inmodal in" id="myModal4" tabindex="-1" role="dialog" style="display: none;" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content animated fadeIn">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only"></span></button>
                    <i class="fa fa-clock-o modal-icon"></i>
                    <h4 class="modal-title">Cadastro de usuário</h4>
                    <small>Campo com * de preenchimento obrigatório.</small>
                </div>
                <div class="modal-body">
                    <div class="alert alert-danger" id="alert_danger_form_usuario"></div>
                    <form method="POST">

                        <div class="row">
                            <div class="col-lg-12" >
                                <label class="font-noraml" for="nome">* Nome</label>
                                <input class="form-control" type="text" required="true" name="nome" id="nome">
                            </div>
                            <div class="col-lg-12" >
                                <label class="font-noraml" for="email">* E-mail</label>
                                <input type="email" class="form-control" name="email" id="email">
                            </div>
                            <div class="col-lg-12" >
                                <label class="font-noraml" for="preco">* Senha</label>
                                <input class="form-control" type="password" required="true" name="senha" id="senha">
                            </div>
                            <div class="col-lg-12" >
                                <label class="font-noraml" for="status">* Status</label>
                                <select class="form-control" name="status" id="status">
                                    <option value="1">Ativo</option>
                                    <option value="0">Inativo</option>
                                </select>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <input type="hidden" name="acao" id="acao">
                    <button type="button" class="btn btn-white" data-dismiss="modal">Fechar</button>
                    <button type="button" onclick="create_user()" id="create-user" class="btn btn-primary">Enviar</button>
                </div>
            </div>
        </div>
    </div>
</body>
<script type="text/javascript">
    $(document).ready(function () {
        $('#alert_danger_form_usuario').hide();
        $('#searchresults').DataTable();
        getMarca();
    });

    function loadUsuario(usua_codigo) {
        var url = "/rest-api/Usuario/" + usua_codigo;
        $.ajax({
            type: "GET",
            url: url,
            success: function (data) {
                console.log(data);
                $('#nome').val(data.usua_nome);
                $('#email').val(data.usua_email);
                $('#senha').val(data.usua_senha);
                $('#status').val(data.usua_habilitado);
                $('#acao').val(data.usua_codigo);
                $('#myModal4').modal('show');
            },
            error: function (error) {
                console.log(error);
            },
            dataType: 'JSON'
        });
    }
    function getMarca() {
        var url = "/rest-api/Marca";
        $.ajax({
            type: "GET",
            url: url,
            success: function (data) {
                var html_option = $('#marca_usuario').html();
                for (var i = 0; i < data.length; i++) {
                    html_option += "<option value='" + data[i].marc_codigo + "' >" + data[i].marc_nome + " </option>";
                }
                $('#marca_usuario').html(html_option);
            },
            error: function (error) {
                console.log(error);
            },
            dataType: 'JSON'
        });
    }
    function create_user() {
        var validacao = isFormValid();
        if (validacao == "") {
            var acao = trim($('#acao').val());
            var url = "/rest-api/Usuario";
            if (acao.length > 0) {
                url += '/' + $('#acao').val();
            }
            console.log(url);
            var usua_nome = $('#nome').val();
            var usua_email = $('#email').val();
            var usua_senha = $('#senha').val();
            var usua_habilitado = $('#status').val();
            var data = {usua_nome: usua_nome, usua_email: usua_email, usua_senha: usua_senha, usua_habilitado: usua_habilitado};
            $.ajax({
                type: "POST",
                url: url,
                data: data,
                success: function (data) {
                    if (data.status == 'SUCCESS') {
                        swal({
                            title: 'SUCESSO!',
                            text: 'Usuário foi cadastrado com sucesso!',
                            type: 'success',
                            closeOnConfirm: false
                        }, function () {
                            window.location.href = "http://localhost/rest-api/Usuario/lista";
                        });

                    } else {
                        swal("INFORMAÇÃO", "Usuário já existente na base de dados", "info");
                    }
                },
                error: function (error) {
                    swal("INFORMAÇÃO", "Usuário já existente na base de dados", "info");
                },
                dataType: 'JSON'
            });
        }
    }
    function isFormValid() {
        var returned = "";
        var nome = trim($('#nome').val());
        var email = trim($('#email').val());
        var senha = trim($('#senha').val());

        if (nome.length == 0) {
            $('#nome').addClass('form_error_input_cashier');
            returned += "<li>Nome do usuario de preenchimento obrigatório!</li>";
        } else {
            $('#nome').removeClass('form_error_input_cashier');
        }
        if (email == 0) {
            $('#email').addClass('form_error_input_cashier');
            returned += "<li>Email do usuario de preenchimento obrigatório!</li>";
        } else {
            $('#email').removeClass('form_error_input_cashier');
        }
        if (senha.length == 0) {
            $('#senha').addClass('form_error_input_cashier');
            returned += "<li>Senha do usuario de preenchimento obrigatório!</li>";
        } else {
            $('#senha').removeClass('form_error_input_cashier');
        }

        if (returned != "") {
            $('#alert_danger_form_usuario').show();
            $('#alert_danger_form_usuario').html('<ul>' + returned + '</ul>');
        } else {
            $('#alert_danger_form_usuario').hide();
            $('#alert_danger_form_usuario').html(returned);
        }
        if ($('#alert_danger_form_usuario ul').length > 0) {
            $("#nome").attr('onchange', 'isFormValid();');
            $("#email").attr('onchange', 'isFormValid();');
            $("#senha").attr('onchange', 'isFormValid();');
        } else {
            $("#nome").removeAttr('onchange');
            $("#email").removeAttr('onchange');
            $("#senha").removeAttr('onchange');
        }
        return returned;
    }

    function trim(str) {
        return str.replace(/^\s+|\s+$/g, "");
    }

</script>