<head>
    <?php echo $this->tag->javascriptInclude('js/jquery/jquery.min.js') ?>
    <?php echo $this->tag->javascriptInclude('js/bootstrap/bootstrap.min.js') ?>
    <?php echo $this->tag->stylesheetLink('css/bootstrap/bootstrap.css') ?>

</head>
<body>
    <div class="row"><br><br></div>
    <div class="row">
        <div class="col-xs-4 col-sm-offset-4">
            <form class="form-horizontal" action="Login/autentica" method="POST">
                <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">Email</label>
                    <div class="col-sm-10">
                        <input type="email" required="true" class="form-control" id="email" name="email" placeholder="Email">
                    </div>
                </div>
                <div class="form-group">
                    <label for="senha" class="col-sm-2 control-label">Password</label>
                    <div class="col-sm-10">
                        <input type="password" required="true" class="form-control" id="senha" name="senha" placeholder="Password">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">Sign in</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>